language: php

php:
  - 5.6
  - 7.1

env:
  global:
    - PLUGIN_NAME=CakeExtendTest
    - CAKE_REF=2.10.11
    - REQUIRE="anklimsk/cakephp-basic-functions:^0.4"
    - DB=mysql
    - COMPOSER_HOME=/home/travis/.composer

matrix:
  include:
    - php: 5.6
      env:
        - CODECOVERAGE=1
    - php: 5.6
      env:
        - PHPCS=1
    - php: 7.1

before_script:
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - travis_wait ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
